Aggiunto install ntp

diff --git a/install b/install
--- a/install
+++ b/install
@@ -106,6 +106,12 @@ if [[ ! "${omvInstall}" == "ii" ]]; then
     exit 2
   fi
 
+  echo "Install ntp..."
+  if ! apt-get --yes install ntp; then
+    echo "failed to install ntp package."
+    exit 2
+  fi
+
   echo "Installing openmediavault..."
   aptFlags="--yes --auto-remove --show-upgraded --allow-downgrades --allow-change-held-packages --no-install-recommends"
   cmd="apt-get ${aptFlags} install openmediavault"
